In [1]:
import chromadb
import pandas as pd
from langchain.docstore.document import Document
client = chromadb.PersistentClient(path="chroma-data")
collection = client.get_collection(name="eidc-metadata")
result = collection.get()
titles = [metadata["dataset_title"] for metadata in result["metadatas"]]

docs = [Document(page_content=result["documents"][i], metadata=result["metadatas"][i]) for i in range(len(result["documents"]))]
for doc in docs:
    doc.metadata["filename"] = doc.metadata["dataset_id"]
    doc.metadata["source"] = doc.metadata["dataset_id"]
docs = docs[:20]
len(docs)

20

In [2]:
from langchain_community.embeddings import OllamaEmbeddings
from langchain_community.chat_models import ChatOllama
llm = ChatOllama(model='mistral-nemo', num_ctx=16384)
embeddings = OllamaEmbeddings(model='mistral-nemo', num_ctx=16384)

In [3]:
from ragas.testset.generator import TestsetGenerator
from ragas.testset.evolutions import simple, reasoning, multi_context
from ragas.run_config import RunConfig
gen = TestsetGenerator.from_langchain(llm, llm, embeddings, run_config=RunConfig(max_workers=1, max_retries=1))
dist = {simple: 0.6, multi_context: 0.2, reasoning: 0.2}

In [4]:
import logging
import nest_asyncio
nest_asyncio.apply()
#logging.basicConfig(level=logging.INFO)
testset = gen.generate_with_langchain_docs(docs, 5, dist, is_async=False)

embedding nodes:   0%|          | 0/40 [00:00<?, ?it/s]

Filename and doc_id are the same for all nodes.

Generating:   0%|          | 0/5 [00:00<?, ?it/s]

max retries exceeded for SimpleEvolution(generator_llm=LangchainLLMWrapper(run_config=RunConfig(timeout=60, max_retries=15, max_wait=90, max_workers=16, thread_timeout=80.0, exception_types=(<class 'Exception'>,), log_tenacity=False)), docstore=InMemoryDocumentStore(splitter=<langchain_text_splitters.base.TokenTextSplitter object at 0x7bdba40f1d60>, nodes=[Node(metadata={'dataset_id': 'ad7babc3-6b43-4754-8981-edcf03769f11', 'dataset_title': 'Countryside Survey 1998 mapped estimates of Broad Habitat areas in Great Britain', 'eidc_metadata_key': 'description', 'filename': 'ad7babc3-6b43-4754-8981-edcf03769f11', 'source': 'ad7babc3-6b43-4754-8981-edcf03769f11'}, page_content='The dataset entitled "Countryside Survey 1998 mapped estimates of Broad Habitat areas in Great Britain" contains the following information in it\'s "description" metadata field: This dataset consists of stock (area) data for Broad Habitats across Great Britain in 1998 in a 1km grid format. The data are national estimates generated by analysing the sample data from 569 1km squares surveyed for the Countryside Survey long term monitoring project, then scaling up to a national level. The data are presented as percent habitat per 1km square for 17 different habitat types. The Countryside Survey is a unique study or \'audit\' of the natural resources of the UK\'s countryside. The sample sites are chosen from a stratified random sample, based on a 15 by 15 km grid of GB. Surveys have been carried out in 1978, 1984, 1990, 1998 and 2007 with repeated visits to the majority of squares. The countryside is sampled and surveyed using rigorous scientific methods, allowing us to compare new results with those from previous surveys. In this way we can detect the gradual and subtle changes that occur in the UK\'s countryside over time. In addition to habitat areas, vegetation species data, soil data, linear habitat data, and freshwater habitat data are also gathered by Countryside Survey.', doc_id='60611c57-96d5-4713-812e-76f93d49a563'), Node(metadata={'dataset_id': '399ed9b1-bf59-4d85-9832-ee4d29f49bfb', 'dataset_title': 'Daily and sub-daily hydrometeorological and soil data (2013-2023) [COSMOS-UK]', 'eidc_metadata_key': 'description', 'filename': '399ed9b1-bf59-4d85-9832-ee4d29f49bfb', 'source': '399ed9b1-bf59-4d85-9832-ee4d29f49bfb'}, page_content='The dataset entitled "Daily and sub-daily hydrometeorological and soil data (2013-2023) [COSMOS-UK]" contains the following information in it\'s "description" metadata field: This dataset contains daily and sub-daily hydrometeorological and soil moisture observations from COSMOS-UK (cosmic-ray soil moisture) monitoring network from October 2013 to the end of 2023. These data are from 51 sites across the UK recording a range of hydrometeorological and soil variables.\n\nEach site in the network records the following hydrometeorological and soil data at 30-minute resolution: Radiation (short wave, long wave, and net), precipitation, atmospheric pressure, air temperature, wind speed and direction, humidity, soil heat flux, and soil temperature and volumetric water content (VWC), measured by point sensors at various depths.\n\nEach site hosts a cosmic-ray sensing probe; a novel sensor technology which counts fast neutrons in the surrounding atmosphere. In combination with the recorded hydrometeorological data, neutron counts are used to derive VWC over a field scale (COSMOS VWC), provide at daily resolution.\n\nThe presence of snow leads to erroneously high measurements of COSMOS VWC due to all the extra water in the surrounding area. Included in the daily data are indications of snow days, on which, the COSMOS VWC are adjusted, and the snow water equivalent (SWE) is given.\n\nThe potential evapotranspiration (PE), derived from recorded hydrometeorological and soil are also included at daily resolution.\n\nTwo levels of quality control are carried out, firstly data is run through a series of automated checks, such as range tests and spike tests, and then all data is manually inspected each week where any other faults are picked up, including sensor faults or connection issues. Quality control flags are provided for all recorded (30 minute) data, indicating the reason for any missing data.\n\nThis work was supported by the Natural Environment Research Council award number NE/R016429/1 as part of the UK-SCAPE programme delivering National Capability.\n\n', doc_id='af465ddb-aaeb-4941-b650-0919d3d9528a', wins=2), Node(metadata={'dataset_id': 'd7da6cb9-104b-4dbc-b709-c1f7ba94fb16', 'dataset_title': 'Woody linear features framework, Great Britain v.1.0', 'eidc_metadata_key': 'description', 'filename': 'd7da6cb9-104b-4dbc-b709-c1f7ba94fb16', 'source': 'd7da6cb9-104b-4dbc-b709-c1f7ba94fb16'}, page_content='The dataset entitled "Woody linear features framework, Great Britain v.1.0" contains the following information in it\'s "description" metadata field: A modelled dataset derived from a range of national datasets, describing the distribution of woody linear feature boundaries in Great Britain.  The dataset presents linear features which have a high likelihood of being a woody linear feature.  The dataset was created by a predictive model developed at the Centre for Ecology & Hydrology, Lancaster in 2016.', doc_id='a7e0e677-3e15-44fe-b29f-9d5d78502411', wins=1), Node(metadata={'dataset_id': '1e050028-5c55-42f4-a0ea-c895d827b824', 'dataset_title': 'Landscape area data 1998 [Countryside Survey]', 'eidc_metadata_key': 'description', 'filename': '1e050028-5c55-42f4-a0ea-c895d827b824', 'source': '1e050028-5c55-42f4-a0ea-c895d827b824'}, page_content='The dataset entitled "Landscape area data 1998 [Countryside Survey]" contains the following information in it\'s "description" metadata field: This dataset consists of stock (area) data for landscape features across Great Britain in 1998. Data are presented as areas of Broad (or Priority) Habitats, with associated landscape attributes (such as plant species and land use), within a set of 569 1km squares across Great Britain.\n\nThe Countryside Survey is a unique study or \'audit\' of the natural resources of the UK\'s countryside. The sample sites are chosen from a stratified random sample, based on a 15 by 15 km grid of GB. Surveys have been carried out in 1978, 1984, 1990, 1998 and 2007 by the Centre for Ecology & Hydrology, with repeated visits to the majority of squares. The countryside is sampled and surveyed using rigorous scientific methods, allowing us to compare new results with those from previous surveys. In this way we can detect the gradual and subtle changes that occur in the UK\'s countryside over time. In addition to habitat areas, vegetation species data, soil data, linear habitat data, and freshwater habitat data are also gathered by Countryside Survey.', doc_id='4f512dfb-29a0-438b-9f95-405c933528b8'), Node(metadata={'dataset_id': '6c8b8134-a877-41ee-aede-f480c7aaa80d', 'dataset_title': 'Stable oxygen and hydrogen isotope composition of precipitation, river water and lake water in the Five Lakes of Mikata catchment, 2011-2012 and 2020-2022', 'eidc_metadata_key': 'description', 'filename': '6c8b8134-a877-41ee-aede-f480c7aaa80d', 'source': '6c8b8134-a877-41ee-aede-f480c7aaa80d'}, page_content='The dataset entitled "Stable oxygen and hydrogen isotope composition of precipitation, river water and lake water in the Five Lakes of Mikata catchment, 2011-2012 and 2020-2022" contains the following information in it\'s "description" metadata field: This dataset contains information about the stable oxygen and hydrogen isotope composition (δ18O, δ2H and d-excess) of waters within the Five Lakes of Mikata catchment. Datapoints span March 2011 – January 2012 and July 2020 – July 2022. Samples include precipitation on an event-basis, weekly river water and weekly lake water. To accompany the precipitation isotope composition data, total precipitation and average temperature during each subsampling period is provided. Water temperature and salinity variations with depth within Lake Suigetsu on six dates across the 2020 – 2022 sampling interval are also given. This data was collected to determine if catchment water composition reflects East Asian Monsoon variability. \n\nThis work was supported by an Australian Research Council Discovery Project (DP200101768), a JSPS KAKENHI Grant (19K20442) and the NERC IAPETUS2 Doctoral Training Partnership.', doc_id='9ac5e304-8172-46b8-9cdb-8e5f1a93583a', wins=1), Node(metadata={'dataset_id': 'b9756c4c-9894-4147-a260-a79067604a06', 'dataset_title': 'Rift Valley fever virus seroprevalence data from cattle, sheep and goats sampled in a cross sectional survey in Tana River County, Kenya (2013)', 'eidc_metadata_key': 'description', 'filename': 'b9756c4c-9894-4147-a260-a79067604a06', 'source': 'b9756c4c-9894-4147-a260-a79067604a06'}, page_content='The dataset entitled "Rift Valley fever virus seroprevalence data from cattle, sheep and goats sampled in a cross sectional survey in Tana River County, Kenya (2013)" contains the following information in it\'s "description" metadata field: These data provide results from serological analysis carried out on serum collected from cattle (sample number = 460), goats (sample number = 949) and sheep (Sample number = 574) combined with data collected at the household and subject/animal levels at the time of serum sampling. The data collected at the household and subject/animal levels were:  the total number of livestock owned by a household, altitude, geographical coordinates of the sampling sites; and breed, age, sex and body condition score of an animal. The research was carried out in irrigated and non-irrigated areas in Tana River County, Kenya. Field surveys were implemented in August to November 2013 and laboratory analyses were completed in June 2015. Serum samples were harvested from blood samples obtained from animals and screened for anti-Rift Valley Fever (RVF) virus immunoglobulin G using inhibition (enzyme-linked immunosorbent assay) ELISA immunoassay. The household data was collected using Open Data Kit (ODK) loaded into smart phones. The serological analysis was performed to determine the risk of Rift Valley Fever virus exposure in cattle, sheep and goats. The aim of the survey was to investigate whether land use change, specifically the conversion of rangeland into cropland, affected RVF exposure pattern in livestock.  \n\nThe data were collected by experienced researchers from the Ministry of Livestock Development Nairobi, Kenya and the International Livestock Research Institute (Kenya). \n\nThis dataset is part of a wider research project, the Dynamic Drivers of Disease in Africa Consortium (DDDAC). The research was funded by NERC project no NE-J001570-1 with support from the Ecosystem Services for Poverty Alleviation Programme (ESPA). Additional funding was provided by Consultative Group on International Agricultural Research (CGIAR) Research Program Agriculture for Nutrition and Health led by International Food Policy Research Institute (IFPRI). ', doc_id='10c77021-da69-4b00-a1c0-ebeeed21e84d'), Node(metadata={'dataset_id': '453fdf49-7328-42ec-94b7-1cebf06c51e2', 'dataset_title': 'Windermere monthly temperatures 1946-2012', 'eidc_metadata_key': 'description', 'filename': '453fdf49-7328-42ec-94b7-1cebf06c51e2', 'source': '453fdf49-7328-42ec-94b7-1cebf06c51e2'}, page_content='The dataset entitled "Windermere monthly temperatures 1946-2012" contains the following information in it\'s "description" metadata field: This dataset consists of monthly mean inshore surface water temperature (degrees C) data from Windermere, a lake in northern England. Data collection began in 1933, but data are presented here from 1946 onwards. The data were initially collected by the Freshwater Biological Association (FBA), then by CEH and its predecessor Institute of Freshwater Ecology (IFE) from 1989 to 2003, and subsequently again by FBA. ', doc_id='d26fa079-5e98-4be0-818e-52e091cb62f5'), Node(metadata={'dataset_id': '3458e0b9-5002-4ddb-bcb3-1c7fb08fb70b', 'dataset_title': 'Peat characteristic data from Blanket Peatland in the Flow Country, Caithness and Sutherland, 2018', 'eidc_metadata_key': 'description', 'filename': '3458e0b9-5002-4ddb-bcb3-1c7fb08fb70b', 'source': '3458e0b9-5002-4ddb-bcb3-1c7fb08fb70b'}, page_content='The dataset entitled "Peat characteristic data from Blanket Peatland in the Flow Country, Caithness and Sutherland, 2018" contains the following information in it\'s "description" metadata field: The dataset contains peat core data from 7 sites in a 1km2 upland (RSPB Forsinard Knockfin Heights) and 7 sites in a 1km2 of lowland (Plantlife Munsary) blanket peatland within the Flow Country, Caithness and Sutherland. Data was obtained between October 2018 and January 2019. Also included is peat depth data from Knockfin Heights at 100m spacing and Teabag Index data to assess peat decomposition rates at 47 points.', doc_id='a0f52700-c979-4483-8c2c-65fb09f2bcc5', wins=1), Node(metadata={'dataset_id': '2f835517-253e-4697-b774-ab6ff2c0d3da', 'dataset_title': 'Grid-to-Grid model estimates of river flow for Great Britain driven by observed data (1980 to 2011)', 'eidc_metadata_key': 'description', 'filename': '2f835517-253e-4697-b774-ab6ff2c0d3da', 'source': '2f835517-253e-4697-b774-ab6ff2c0d3da'}, page_content='The dataset entitled "Grid-to-Grid model estimates of river flow for Great Britain driven by observed data (1980 to 2011)" contains the following information in it\'s "description" metadata field: Gridded hydrological model river flow estimates on a 1km grid over Great Britain for the period Dec 1980 - Nov 2011. The dataset includes monthly mean river flow, annual maxima of daily mean river flow (water years Oct - Sept) and annual minima of 7-day mean river flow (years spanning Dec-Nov) (units: m3/s). The data are provided in gridded netCDF files. There is one file for each variable. \n\nTo aid interpretation, two additional spatial datasets are provided: a) digitally-derived catchment areas and b) estimated locations of flow gauging stations both on the 1km x 1km grid. \n\nThe data were produced as part of UK-SCAPE (UK Status, Change And Projections of the Environment; https://ukscape.ceh.ac.uk/, Work Package 2: Case Study - Water) a NERC-funded National Capability Science Single Centre award.\n', doc_id='392579ae-f887-402c-824d-6cf656463686', wins=2), Node(metadata={'dataset_id': 'ee9ab43d-a4fe-4e73-afd5-cd4fc4c82556', 'dataset_title': 'Gridded estimates of daily and monthly areal rainfall for the United Kingdom (1890-2017) [CEH-GEAR]', 'eidc_metadata_key': 'description', 'filename': 'ee9ab43d-a4fe-4e73-afd5-cd4fc4c82556', 'source': 'ee9ab43d-a4fe-4e73-afd5-cd4fc4c82556'}, page_content='The dataset entitled "Gridded estimates of daily and monthly areal rainfall for the United Kingdom (1890-2017) [CEH-GEAR]" contains the following information in it\'s "description" metadata field: 1 km gridded estimates of daily and monthly rainfall for Great-Britain and Northern Ireland (together with approximately 3000 km2 of catchment in the Republic of Ireland) from 1890 to 2017. The rainfall estimates are derived from the Met Office national database of observed precipitation. To derive the estimates, monthly and daily (when complete month available) precipitation totals from the UK rain gauge network are used. The natural neighbour interpolation methodology, including a normalisation step based on average annual rainfall, was used to generate the daily and monthly estimates. The estimated rainfall on a given day refers to the rainfall amount precipitated in 24 hours between 9am on that day until 9am on the following day. The CEH-GEAR dataset has been developed according to the guidance provided in BS 7843-4:2012.', doc_id='be5b2934-8c1a-4daa-9dbb-a018251f6294', wins=1), Node(metadata={'dataset_id': 'd4d5a10e-1612-4bb5-97b2-2b850cccdcb2', 'dataset_title': 'Diffuse agricultural pollution to rivers in Scotland ', 'eidc_metadata_key': 'description', 'filename': 'd4d5a10e-1612-4bb5-97b2-2b850cccdcb2', 'source': 'd4d5a10e-1612-4bb5-97b2-2b850cccdcb2'}, page_content='The dataset entitled "Diffuse agricultural pollution to rivers in Scotland " contains the following information in it\'s "description" metadata field: Modelled predictions of annual pollutant loads in rivers from agricultural source areas for Scotland, reported at Water Framework  Directive (WFD) catchment scale. The modelled pollutants include total phosphorous, nitrate (NO3-N), faecal indicator organisms (FIOs), suspended solids, methane (CH4) and nitrous oxide (N2O) gas emissions. The agricultural source areas include arable land, improved grassland, rough grazing land and others (e.g. steadings, tracks and other non-field losses). Modelled predictions account for current (c. 2012) implementation of General Binding Rules, Nitrate Vulnerable Zone Action Programme and a number of SRDP options. The values specify pollutant losses in 10^6 colony forming units (cfu) per year for FIOs and kilograms per year for the other pollutants.', doc_id='31f3eb9a-086b-4704-87df-471a71cd7a91'), Node(metadata={'dataset_id': '4c591c29-01c9-493b-806e-7253e2682376', 'dataset_title': 'Physico-chemical properties and discharge of a peatland river, Drumtree, Scotland, May 2012 to December 2014', 'eidc_metadata_key': 'description', 'filename': '4c591c29-01c9-493b-806e-7253e2682376', 'source': '4c591c29-01c9-493b-806e-7253e2682376'}, page_content='The dataset entitled "Physico-chemical properties and discharge of a peatland river, Drumtree, Scotland, May 2012 to December 2014" contains the following information in it\'s "description" metadata field: This data set covers high resolution (30-min frequency) water quality and dissolved carbon data from a peatland river in Southwest Scotland (5.8 km2), part of the Whitelee Wind Farm complex. The data set covers approx. 2.5 years including two full hydrological years and 261 individual flood events between 23/05/2012 and 16/12/2014. Carbon data was measured using a Scan Spectrolyser – a field deployable UV-Vis light spectrometer. ', doc_id='cf59486e-174e-40a4-a389-7f6f884f55a8'), Node(metadata={'dataset_id': 'ac271791-b722-489c-9b68-b37316ec826c', 'dataset_title': 'UK public perceptions around invasive species and biosecurity before and one year after undertaking e-Learning, 2015-2018', 'eidc_metadata_key': 'description', 'filename': 'ac271791-b722-489c-9b68-b37316ec826c', 'source': 'ac271791-b722-489c-9b68-b37316ec826c'}, page_content='The dataset entitled "UK public perceptions around invasive species and biosecurity before and one year after undertaking e-Learning, 2015-2018" contains the following information in it\'s "description" metadata field: This data contains the results of student and professional perceptions surveys conducted in the UK before and after e-Learning training, as part of a project to determine the effectiveness of e-Learning as a training tool. The dataset include two surveys; before and after e-Learning training. Students and professionals were given two separate surveys which were combined to create one dataset. The surveys were collected between September 2015 and July 2018.\n\nThe objective of the survey was to collect data on participants’ awareness, risk perceptions and self-reported behaviours on biosecurity for invasive species. The topics on both the before and after survey included age, role at institution, field of work/study, field activity environments, cleaning methods for equipment, outerwear/footwear and transport and awareness and perceptions of risk around invasive species and biosecurity campaigns. The data does not include the aggregated cleaning scores that were used for the analysis nor has it excluded any participants that were not used in the final data analysis. The dataset has been anonymised by removing names of respondents, email addresses, departments or organisations worked for or s

In [5]:
df = testset.to_pandas()
df.to_csv("eidc_rag_test_set.csv", index=False)

In [6]:
df

,question,contexts,ground_truth
0,What are the spatial and temporal coverage of ...,"[The dataset entitled ""Gridded estimates of da...",The spatial coverage of the gridded estimates ...
1,What are the 21 land cover classes in the 'Lan...,"[The dataset entitled ""Land Cover Map 2020 (10...",The answer to given question is not present in...
2,Where was the predictive model used to create ...,"[The dataset entitled ""Woody linear features f...",The predictive model was developed at the Cent...
3,What sensors & auto-checks in COSMOS-UK mitiga...,"[The dataset entitled ""Daily and sub-daily hyd...",The presence of snow leads to erroneously high...

In [29]:
df = pd.read_csv("ragas-testset.csv")
df

,question,contexts,ground_truth,evolution_type,metadata,episode_done
0,What was the average weed abundance across the...,"['The dataset entitled ""Abundance of weeds in ...",The answer to given question is not present in...,simple,[{'dataset_id': '6762f1b5-2bcc-4062-bff6-e560d...,True
1,How many harvests were conducted in total to m...,"['The dataset entitled ""Grass productivity dat...",Three different harvests were conducted in tot...,simple,[{'dataset_id': '6e395915-ab5c-43f4-b4de-c9a3c...,True
2,What specific parameters are recorded for each...,"['The dataset entitled ""UK Environmental Chang...",The specific parameters recorded for each tree...,simple,[{'dataset_id': '94aef007-634e-42db-bc52-9aae8...,True
3,What are the specific types of structures and ...,"['The dataset entitled ""Building, infrastructu...",The GIS shapefiles include information about b...,simple,[{'dataset_id': 'a763e254-c249-4934-b0fb-c3b80...,True
4,What are the estimated annual loads of nitroge...,"['The dataset entitled ""Non-agricultural pollu...",The answer to given question is not present in...,simple,[{'dataset_id': 'eb73ca31-7eb9-479c-96be-6063e...,True
...,...,...,...,...,...,...
95,What are the water quality parameters measured...,"['The dataset entitled ""Weekly water quality d...",The water quality parameters measured in the d...,simple,[{'dataset_id': 'cf10ea9a-a249-4074-ac0c-e0c30...,True
96,What are the four scenarios projected for land...,"['The dataset entitled "" Land use maps under t...",The four scenarios projected for land use in t...,simple,[{'dataset_id': 'a94640dc-fe21-4c38-936b-d62df...,True
97,What were the national estimates of Broad Habi...,"['The dataset entitled ""Countryside Survey 199...",The national estimates of Broad Habitat areas ...,simple,[{'dataset_id': '53ef00f4-e0c5-4095-850e-d4c47...,True
98,What does the 'Generate_data_for_island_model_...,"['The dataset entitled ""Code for generating da...",The 'Generate_data_for_island_model_weak_selec...,simple,[{'dataset_id': 'aec1e55f-f6ac-4673-9e93-706b4...,True
99,What are the different years for which land co...,"['The dataset entitled ""Land Cover Map 1990 (1...",The different years for which land cover maps ...,simple,[{'dataset_id': 'f5e3bd00-efd0-4dc6-a454-aa597...,True

In [30]:
from rag.wrappers import RagPipelineWrapper
import yaml
with open("config.yml", "r") as config_file:
    config = yaml.safe_load(config_file)
pipeline_file = f"{config["pipelines-dir"]}/{config["rag-demo"]["pipeline"]}"
chroma_path = config["vector-db"]["path"]
collection = config["vector-db"]["collection"]
prompt = config["rag-demo"]["prompt"]
rag_pipe = RagPipelineWrapper(
    pipeline_file,
    chroma_path=chroma_path,
    collection=collection,
    prompt=prompt,
)

In [31]:
eval_output = []
for i, row in df.sample(30).iterrows():
    answer, documents = rag_pipe.query_get_contexts(row["question"])
    result = {
        "question": row["question"],
        "ground_truth": row["ground_truth"],
        "answer": answer,
        "contexts": [doc.content for doc in documents],
    }
    eval_output.append(result)
eval_df = pd.DataFrame(eval_output)

In [32]:
from datasets import Dataset
eval_dataset = Dataset.from_pandas(eval_df)

In [33]:
eval_dataset

Dataset({
    features: ['question', 'ground_truth', 'answer', 'contexts'],
    num_rows: 30
})

In [34]:
from ragas.metrics import (
    faithfulness,
    answer_relevancy,
    context_precision,
    context_utilization,
    context_recall,
    context_entity_recall,
    answer_similarity,
    answer_correctness,
)
from ragas import evaluate
from ragas.run_config import RunConfig
import nest_asyncio

nest_asyncio.apply()
result = evaluate(
    eval_dataset,
    metrics=[
        faithfulness,
        answer_relevancy,
        context_precision,
        context_utilization,
        context_recall,
        context_entity_recall,
        answer_similarity,
        answer_correctness,
    ],
    llm=llm,
    embeddings=embeddings,
    is_async=False,
    raise_exceptions=False,
    run_config=RunConfig(max_workers=1),
)
result

Evaluating:   0%|          | 0/240 [00:00<?, ?it/s]

Failed to parse output. Returning None.

{'faithfulness': 0.6308, 'answer_relevancy': 0.3331, 'context_precision': 0.5328, 'context_utilization': 0.5302, 'context_recall': 0.7146, 'context_entity_recall': 0.2554, 'answer_similarity': 0.2784, 'answer_correctness': 0.2502}

In [35]:
eval_results = result.to_pandas()

In [42]:
import plotly.graph_objects as go
import plotly.io as pio
pio.templates.default = "gridon"
fig = go.Figure()
metrics = [metric for metric in eval_results.columns.to_list() if metric not in ["question", "ground_truth", "answer", "contexts"]]
for metric in metrics:
    fig.add_trace(go.Violin(y=eval_results[metric], name=metric, points="all", box_visible=True, meanline_visible=True))
fig.update_layout(title_text="RAG Evaluation Metrics (LLama 3.1)")
fig.update_yaxes(range=[-0.02,1.02])
fig.show()